### ISSUE TITLE
Unable to find 'z3' engine

### ISSUE THREAD

**Issue by hutch31** [YosysHQ/SymbiYosys#6]
I'm running through the "hello" example from Clifford's talk on Yosys formal verification.  When I attempt to run the example it looks like it's not able to find the formal engines.  I also tried the "yices" solver with the same result.

Is there an extra flag/step/library required to build the formal engines in yosys?

yosys version: 08225f49a410c7df6d7d6fe098a4dabc68789ac5
SymbiYosys version: c003a1b078050e5134ef5519a3f34149eb6471f1

```
SBY 15:09:07 [hello] engine_0.basecase: File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
SBY 15:09:07 [hello] engine_0.basecase: restore_signals, start_new_session)
SBY 15:09:07 [hello] engine_0.basecase: File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
SBY 15:09:07 [hello] engine_0.basecase: raise child_exception_type(errno_num, err_msg)
SBY 15:09:07 [hello] engine_0.basecase: FileNotFoundError: [Errno 2] No such file or directory: 'z3'
SBY 15:09:07 [hello] engine_0.induction: Traceback (most recent call last):
SBY 15:09:07 [hello] engine_0.induction: File "/usr/local/bin/yosys-smtbmc", line 392, in <module>
SBY 15:09:07 [hello] engine_0.induction: smt.write(line)
SBY 15:09:07 [hello] engine_0.induction: File "/usr/local/bin/../share/yosys/python3/smtio.py", line 333, in write
SBY 15:09:07 [hello] engine_0.induction: self.setup()
SBY 15:09:07 [hello] engine_0.induction: File "/usr/local/bin/../share/yosys/python3/smtio.py", line 188, in setup
SBY 15:09:07 [hello] engine_0.induction: self.p_open()
SBY 15:09:07 [hello] engine_0.induction: File "/usr/local/bin/../share/yosys/python3/smtio.py", line 282, in p_open
SBY 15:09:07 [hello] engine_0.induction: self.p = subprocess.Popen(self.popen_vargs, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
SBY 15:09:07 [hello] engine_0.induction: File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
SBY 15:09:07 [hello] engine_0.induction: restore_signals, start_new_session)
SBY 15:09:07 [hello] engine_0.induction: File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
SBY 15:09:07 [hello] engine_0.induction: raise child_exception_type(errno_num, err_msg)
SBY 15:09:07 [hello] engine_0.induction: FileNotFoundError: [Errno 2] No such file or directory: 'z3'
SBY 15:09:07 [hello] engine_0.basecase: finished (returncode=1)
Traceback (most recent call last):
  File "/usr/local/bin/sby", line 248, in <module>
    retcode += run_job(t)
  File "/usr/local/bin/sby", line 235, in run_job
    job.run()
  File "/usr/local/bin/../share/yosys/python3/sby_core.py", line 496, in run
    self.taskloop()
  File "/usr/local/bin/../share/yosys/python3/sby_core.py", line 271, in taskloop
    task.poll()
  File "/usr/local/bin/../share/yosys/python3/sby_core.py", line 115, in poll
    self.handle_exit(self.p.returncode)
  File "/usr/local/bin/../share/yosys/python3/sby_core.py", line 71, in handle_exit
    self.exit_callback(retcode)
  File "/usr/local/bin/../share/yosys/python3/sby_engine_smtbmc.py", line 147, in exit_callback
    assert task_status is not None
AssertionError
```

[hello.zip](https://github.com/YosysHQ/SymbiYosys/files/1808832/hello.zip)

**Comment by cliffordwolf** [comment]
You have to install z3 (and the other solvers if you want to use them). See http://symbiyosys.readthedocs.io/en/latest/quickstart.html#z3.
